version: '1.0'
stages:
  - prepare
  - package
  - deploy
steps:
  main_clone:
    title: 'Cloning main repository...'
    type: git-clone
    repo: 'davidquiros-codefresh/call-child-pipeline-sample-app'
    revision: '${{CF_REVISION}}'
    git: github
    stage: prepare
  read_my_app_version:
    title: Reading Application version
    stage: prepare
    image: node:latest
    commands:
      - export PACKAGE_VERSION=$(node -p "require('./package.json').version")
      - cf_export PACKAGE_VERSION
  build_my_docker_image:
    title: 'Building My Docker Image'
    stage: package
    type: build
    dockerfile: Dockerfile
    image_name: my-app-image
    tag: ${{PACKAGE_VERSION}}
  call_qa_pipeline:
    title: Deploy to QA
    stage: deploy
    type: codefresh-run
    arguments:
      PIPELINE_ID: 5e1cc9b06e1ebe2d5dd385ed
      TRIGGER_ID: 'call-child-pipeline-sample-app'
      VARIABLE:
        - CF_BRANCH=${{CF_BRANCH}}
        - CF_REVISION=${{CF_REVISION}}
        - APP_VERSION=${{PACKAGE_VERSION}}
    when:
      branch:
        only:
          - develop      
  call_prod_pipeline:
    title: Deploy to QA
    stage: deploy
    type: codefresh-run
    arguments:
      PIPELINE_ID: 5e1ccb466baea5ad3dde8693
      TRIGGER_ID: 'call-child-pipeline-sample-app'
        - CF_BRANCH=${{CF_BRANCH}}
        - CF_REVISION=${{CF_REVISION}}
        - APP_VERSION=${{PACKAGE_VERSION}}
    when:
      branch:
        only:
          - /^release.*/i     
    
